/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type {
  DefaultSelectionPrisma36ProfilePayload,
  ProfileDto,
  UpdateProfileDto
} from "../../model";

import { customInstance } from "../../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getProfiles = () => {
  const getMyProfile = (options?: SecondParameter<typeof customInstance>) => {
    return customInstance<ProfileDto>(
      { url: `/profiles/me`, method: "GET" },
      options
    );
  };
  const updateMyProfile = (
    updateProfileDto: UpdateProfileDto,
    options?: SecondParameter<typeof customInstance>
  ) => {
    return customInstance<DefaultSelectionPrisma36ProfilePayload>(
      {
        url: `/profiles/me`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateProfileDto
      },
      options
    );
  };
  const getProfileByUserId = (
    userId: string,
    options?: SecondParameter<typeof customInstance>
  ) => {
    return customInstance<DefaultSelectionPrisma36ProfilePayload>(
      { url: `/profiles/users/${userId}`, method: "GET" },
      options
    );
  };
  return { getMyProfile, updateMyProfile, getProfileByUserId };
};
export type GetMyProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfiles>["getMyProfile"]>>
>;
export type UpdateMyProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfiles>["updateMyProfile"]>>
>;
export type GetProfileByUserIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getProfiles>["getProfileByUserId"]>>
>;
