/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsFilePurpose =
  (typeof _36EnumsFilePurpose)[keyof typeof _36EnumsFilePurpose];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsFilePurpose = {
  OTHER: "OTHER",
  VIDEO_RAW: "VIDEO_RAW",
  VIDEO_FINAL: "VIDEO_FINAL",
  AVATAR: "AVATAR",
  IMAGE: "IMAGE",
  DOCUMENT: "DOCUMENT",
  ATTACHMENT: "ATTACHMENT",
  SUBMISSION: "SUBMISSION",
  FEEDBACK_AUDIO: "FEEDBACK_AUDIO"
} as const;
