/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsPaymentStatus =
  (typeof _36EnumsPaymentStatus)[keyof typeof _36EnumsPaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsPaymentStatus = {
  COMPLETED: "COMPLETED",
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
} as const;
