/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsFeedbackStatus =
  (typeof _36EnumsFeedbackStatus)[keyof typeof _36EnumsFeedbackStatus];

export const _36EnumsFeedbackStatus = {
  OPEN: "OPEN",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  RESOLVED: "RESOLVED",
  DECLINED: "DECLINED"
} as const;
