/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsUserAvalabilityStatus =
  (typeof _36EnumsUserAvalabilityStatus)[keyof typeof _36EnumsUserAvalabilityStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsUserAvalabilityStatus = {
  AVAILABLE: "AVAILABLE",
  BUSY: "BUSY",
  ON_VACATION: "ON_VACATION",
  UNAVAILABLE: "UNAVAILABLE"
} as const;
