/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsSubmissionType =
  (typeof _36EnumsSubmissionType)[keyof typeof _36EnumsSubmissionType];

export const _36EnumsSubmissionType = {
  FILE_UPLOAD: "FILE_UPLOAD",
  URL_LINK: "URL_LINK",
  TEXT_CONTENT: "TEXT_CONTENT",
  MIXED: "MIXED"
} as const;
