/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsTaskStatus =
  (typeof _36EnumsTaskStatus)[keyof typeof _36EnumsTaskStatus];

export const _36EnumsTaskStatus = {
  REVIEW: "REVIEW",
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  DONE: "DONE"
} as const;
