/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsNotificationType =
  (typeof _36EnumsNotificationType)[keyof typeof _36EnumsNotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsNotificationType = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_ASSIGNED: "PROJECT_ASSIGNED",
  PROJECT_STATUS_UPDATED: "PROJECT_STATUS_UPDATED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  NEW_MESSAGE: "NEW_MESSAGE",
  FEEDBACK_RECEIVED: "FEEDBACK_RECEIVED",
  FEEDBACK_RESOLVED: "FEEDBACK_RESOLVED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_COMPLETED: "TASK_COMPLETED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_PROCESSED: "PAYMENT_PROCESSED",
  SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT"
} as const;
