/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsRole = (typeof _36EnumsRole)[keyof typeof _36EnumsRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsRole = {
  CLIENT: "CLIENT",
  FREELANCER: "FREELANCER",
  ADMIN: "ADMIN"
} as const;
