/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsSubmissionStatus =
  (typeof _36EnumsSubmissionStatus)[keyof typeof _36EnumsSubmissionStatus];

export const _36EnumsSubmissionStatus = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REVISION_REQUIRED: "REVISION_REQUIRED",
  REJECTED: "REJECTED"
} as const;
