/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsFeedbackType =
  (typeof _36EnumsFeedbackType)[keyof typeof _36EnumsFeedbackType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsFeedbackType = {
  GENERAL: "GENERAL",
  SPECIFIC: "SPECIFIC",
  REVISION_REQUEST: "REVISION_REQUEST",
  APPROVAL: "APPROVAL"
} as const;
