/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsProjectStatus =
  (typeof _36EnumsProjectStatus)[keyof typeof _36EnumsProjectStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsProjectStatus = {
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  REVIEW: "REVIEW",
  COMPLETED: "COMPLETED"
} as const;
