/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsPriority =
  (typeof _36EnumsPriority)[keyof typeof _36EnumsPriority];

export const _36EnumsPriority = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT"
} as const;
