/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsProjectType =
  (typeof _36EnumsProjectType)[keyof typeof _36EnumsProjectType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsProjectType = {
  LP_EDIT: "LP_EDIT",
  SEO_ARTICLE: "SEO_ARTICLE",
  THUMBNAIL: "THUMBNAIL",
  FLYER: "FLYER",
  BANNER: "BANNER",
  VIDEO_EDIT: "VIDEO_EDIT",
  SCRIPT: "SCRIPT",
  BUSINESS_CARD: "BUSINESS_CARD",
  INSTAGRAM_POST: "INSTAGRAM_POST",
  LINE_SETUP: "LINE_SETUP",
  OTHER: "OTHER"
} as const;
