/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface AuthTokensDto {
  /** JWT ID token */
  idToken?: string;
  /** JWT access token */
  accessToken?: string;
  /** JWT refresh token */
  refreshToken?: string;
  /** Token expiration time in seconds */
  expiresIn?: number;
  [key: string]: unknown;
}
