/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { BannerRequirementQuantity } from "./bannerRequirementQuantity";
import type { BannerRequirementAssets } from "./bannerRequirementAssets";
import type { BannerRequirementReferences } from "./bannerRequirementReferences";

export interface BannerRequirement {
  types: string[];
  size?: string;
  quantity: BannerRequirementQuantity;
  headline: string;
  subHeadline?: string;
  mandatoryText?: string;
  targetAudience?: string;
  goal: string[];
  designStyle?: string[];
  colorRequirement?: string;
  assets?: BannerRequirementAssets;
  references?: BannerRequirementReferences;
  midReviewSchedule?: string;
  needsInitialCheck?: boolean;
  agreements: string[];
  [key: string]: unknown;
}
