/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { BannerProjectDtoDueDate } from "./bannerProjectDtoDueDate";
import type { BannerProjectDtoPointsRequired } from "./bannerProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { BannerRequirement } from "./bannerRequirement";

export interface BannerProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: BannerProjectDtoDueDate;
  pointsRequired?: BannerProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: BannerRequirement;
  [key: string]: unknown;
}
