/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessCardRequirementDeliveryFormat } from "./businessCardRequirementDeliveryFormat";
import type { BusinessCardRequirementContact } from "./businessCardRequirementContact";
import type { BusinessCardRequirementAssets } from "./businessCardRequirementAssets";
import type { BusinessCardRequirementReferences } from "./businessCardRequirementReferences";

export interface BusinessCardRequirement {
  quantity: number;
  isDoubleSided: boolean;
  isRequiresPrinting: boolean;
  deliveryFormat: BusinessCardRequirementDeliveryFormat;
  companyName?: string;
  companyLogo?: string;
  positionTitle?: string;
  fullNameKanji: string;
  fullNameKana: string;
  fullNameEnglish?: string;
  contact: BusinessCardRequirementContact;
  designStyle?: string[];
  colorRequirement?: string;
  assets?: BusinessCardRequirementAssets;
  references?: BusinessCardRequirementReferences;
  paperSpecs?: string;
  additionalNotes?: string;
  agreements: string[];
  [key: string]: unknown;
}
