/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessCardProjectDtoDueDate } from "./businessCardProjectDtoDueDate";
import type { BusinessCardProjectDtoPointsRequired } from "./businessCardProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { BusinessCardRequirement } from "./businessCardRequirement";

export interface BusinessCardProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: BusinessCardProjectDtoDueDate;
  pointsRequired?: BusinessCardProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: BusinessCardRequirement;
  [key: string]: unknown;
}
