/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordResponseDto {
  success: boolean;
  message: string;
  [key: string]: unknown;
}
