/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordDto {
  oldPassword: string;
  newPassword: string;
  [key: string]: unknown;
}
