/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36UserPayload } from "./defaultSelectionPrisma36UserPayload";

export interface ConfirmSignUpResponseDto {
  success: boolean;
  user: DefaultSelectionPrisma36UserPayload;
  [key: string]: unknown;
}
