/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface ConnectionResponse {
  id: string;
  name: string;
  email: string;
  role: string;
  bio?: string;
  isOnline: boolean;
  isRealTimeConnected?: boolean;
  minutesOffline?: number;
  lastSeen?: string;
  avatarUrl?: string;
  conversationId: string;
  unreadCount: number;
  projectTitle: string;
  projectId: string;
  companyName?: string;
  [key: string]: unknown;
}
