/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface ConnectionInfo {
  id: string;
  initiatorId: string;
  recipientId: string;
  projectId: string;
  conversationId: string;
  status: string;
  createdAt: string;
  [key: string]: unknown;
}
