/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DirectMessageInfo } from "./directMessageInfo";
import type { ConversationInfoProjectInfo } from "./conversationInfoProjectInfo";

export interface ConversationInfo {
  conversationId: string;
  participantIds: string[];
  lastMessage?: DirectMessageInfo;
  unreadCount: number;
  projectInfo: ConversationInfoProjectInfo;
  [key: string]: unknown;
}
