/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsSubmissionType } from "./_36EnumsSubmissionType";
import type { _36EnumsSubmissionStatus } from "./_36EnumsSubmissionStatus";

export interface CreateSubmissionDto {
  projectId?: string;
  /** @nullable */
  taskId?: string | null;
  title?: string;
  /** @nullable */
  description?: string | null;
  type?: _36EnumsSubmissionType;
  status?: _36EnumsSubmissionStatus;
  files?: string[];
  content?: unknown;
  /** @nullable */
  parentSubmissionId?: string | null;
  version?: number;
  submitterId?: string;
  [key: string]: unknown;
}
