/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTaskDtoTodosAnyOfItem } from "./createTaskDtoTodosAnyOfItem";

/**
 * @nullable
 */
export type CreateTaskDtoTodos = string | CreateTaskDtoTodosAnyOfItem[] | null;
