/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LpEditProjectDto } from "./lpEditProjectDto";
import type { SeoArticleProjectDto } from "./seoArticleProjectDto";
import type { ThumbnailProjectDto } from "./thumbnailProjectDto";
import type { FlyerProjectDto } from "./flyerProjectDto";
import type { BannerProjectDto } from "./bannerProjectDto";
import type { VideoEditProjectDto } from "./videoEditProjectDto";
import type { ScriptProjectDto } from "./scriptProjectDto";
import type { BusinessCardProjectDto } from "./businessCardProjectDto";
import type { InstagramPostProjectDto } from "./instagramPostProjectDto";
import type { LineSetupProjectDto } from "./lineSetupProjectDto";
import type { OtherProjectDto } from "./otherProjectDto";

export type CreateProjectDto =
  | LpEditProjectDto
  | SeoArticleProjectDto
  | ThumbnailProjectDto
  | FlyerProjectDto
  | BannerProjectDto
  | VideoEditProjectDto
  | ScriptProjectDto
  | BusinessCardProjectDto
  | InstagramPostProjectDto
  | LineSetupProjectDto
  | OtherProjectDto;
