/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ConnectionInfo } from "./connectionInfo";

export type CreateConnection200 = {
  error?: string;
  message?: string;
  data?: ConnectionInfo;
  success: boolean;
};
