/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FeedbackTimestamp } from "./feedbackTimestamp";
import type { _36EnumsFeedbackType } from "./_36EnumsFeedbackType";

export interface CreateFeedbackInputDto {
  fileId: string;
  content?: string;
  timestamp?: FeedbackTimestamp[];
  type?: _36EnumsFeedbackType;
  instructionAudioFileId?: string;
  [key: string]: unknown;
}
