/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreateDto } from "./userCreateDto";
import type { CreateUserByAdminBodyAllOf } from "./createUserByAdminBodyAllOf";

export type CreateUserByAdminBody = UserCreateDto & CreateUserByAdminBodyAllOf;
