/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface CreateReviewDto {
  rating: number;
  comment?: string;
  projectId: string;
  revieweeId: string;
  [key: string]: unknown;
}
