/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePaymentDto {
  projectId: string;
  amount: number;
  paymentMethod?: string;
  transactionId?: string;
  description?: string;
  platformFeeRate?: number;
  [key: string]: unknown;
}
