/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsPriority } from "./_36EnumsPriority";
import type { _36EnumsTaskStatus } from "./_36EnumsTaskStatus";
import type { CreateTaskDtoTodos } from "./createTaskDtoTodos";

export interface CreateTaskDto {
  projectId: string;
  assignedToId: string;
  title: string;
  description?: string;
  priority?: _36EnumsPriority;
  status?: _36EnumsTaskStatus;
  dueDate?: string;
  /** @nullable */
  todos?: CreateTaskDtoTodos;
  createdById?: string;
  [key: string]: unknown;
}
