/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface DefaultSelectionPrisma36ReviewPayload {
  revieweeId: string;
  reviewerId: string;
  comment: string;
  rating: number;
  projectId: string;
  updatedAt: string;
  createdAt: string;
  id: string;
}
