/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { Decimal } from "./decimal";
import type { _36EnumsPaymentStatus } from "./_36EnumsPaymentStatus";

export interface DefaultSelectionPrisma36PaymentPayload {
  freelancerAmount: Decimal;
  platformFee: Decimal;
  paymentDate: string;
  transactionId: string;
  paymentMethod: string;
  amount: Decimal;
  projectId: string;
  status: _36EnumsPaymentStatus;
  description: string;
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
  id: string;
}
