/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { JsonValue } from "./jsonValue";
import type { _36EnumsPriority } from "./_36EnumsPriority";
import type { _36EnumsTaskStatus } from "./_36EnumsTaskStatus";

export interface DefaultSelectionPrisma36TaskPayload {
  originFeedbackId: string;
  todos: JsonValue;
  generatedFromOverviewVersion: number;
  priority: _36EnumsPriority;
  assignedToId: string;
  version: number;
  projectId: string;
  status: _36EnumsTaskStatus;
  dueDate: string;
  description: string;
  title: string;
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
  id: string;
}
