/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DirectMessageInfoSender } from "./directMessageInfoSender";
import type { DirectMessageInfoReceiver } from "./directMessageInfoReceiver";
import type { DirectMessageInfoAttachmentsItem } from "./directMessageInfoAttachmentsItem";

export interface DirectMessageInfo {
  id: string;
  senderId: string;
  receiverId: string;
  content: string;
  conversationId: string;
  isRead: boolean;
  hasAttachment: boolean;
  deliveredAt?: string;
  readAt?: string;
  createdAt: string;
  sender?: DirectMessageInfoSender;
  receiver?: DirectMessageInfoReceiver;
  attachments?: DirectMessageInfoAttachmentsItem[];
  [key: string]: unknown;
}
