/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FeedbackDtoTimestamp } from "./feedbackDtoTimestamp";
import type { _36EnumsFeedbackType } from "./_36EnumsFeedbackType";
import type { _36EnumsFeedbackStatus } from "./_36EnumsFeedbackStatus";
import type { PartialSubmissionDto } from "./partialSubmissionDto";

export interface FeedbackDto {
  id: string;
  projectId: string;
  fileId: string;
  createdById: string;
  userName?: string;
  userAvatarUrl?: string;
  content: string;
  /** @nullable */
  timestamp?: FeedbackDtoTimestamp;
  type: _36EnumsFeedbackType;
  status: _36EnumsFeedbackStatus;
  /** @nullable */
  rawContent?: string | null;
  /** @nullable */
  instructionAudioFileId?: string | null;
  submission?: PartialSubmissionDto;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}
