/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsFilePurpose } from "./_36EnumsFilePurpose";
import type { FileDtoUploadedBy } from "./fileDtoUploadedBy";

export interface FileDto {
  id: string;
  /** @nullable */
  entityId: string | null;
  filename: string;
  originalFilename: string;
  mimeType: string;
  filePath: string;
  purpose: _36EnumsFilePurpose;
  fileSize: number;
  version: number;
  /** @nullable */
  description?: string | null;
  uploadUserId: string;
  createdAt: string;
  updatedAt: string;
  uploadedBy?: FileDtoUploadedBy;
  [key: string]: unknown;
}
