/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FlyerProjectDtoDueDate } from "./flyerProjectDtoDueDate";
import type { FlyerProjectDtoPointsRequired } from "./flyerProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { FlyerRequirement } from "./flyerRequirement";

export interface FlyerProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: FlyerProjectDtoDueDate;
  pointsRequired?: FlyerProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: FlyerRequirement;
  [key: string]: unknown;
}
