/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type FlyerRequirementStoreInfoAnyOf = {
  website?: string;
  email?: string;
  phone?: string;
  address: string;
  name: string;
};
