/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FlyerRequirementFlyerSize } from "./flyerRequirementFlyerSize";
import type { FlyerRequirementDeliveryFormat } from "./flyerRequirementDeliveryFormat";
import type { FlyerRequirementStoreInfo } from "./flyerRequirementStoreInfo";
import type { FlyerRequirementAssets } from "./flyerRequirementAssets";
import type { FlyerRequirementReferences } from "./flyerRequirementReferences";
import type { FlyerRequirementQrCodes } from "./flyerRequirementQrCodes";

export interface FlyerRequirement {
  flyerSize: FlyerRequirementFlyerSize;
  isDoubleSided: boolean;
  isRequiresPrinting: boolean;
  quantity?: number;
  deliveryFormat: FlyerRequirementDeliveryFormat;
  catchCopy?: string;
  serviceDescription: string;
  storeInfo?: FlyerRequirementStoreInfo;
  assets?: FlyerRequirementAssets;
  references?: FlyerRequirementReferences;
  qrCodes?: FlyerRequirementQrCodes;
  designStyle?: string[];
  colorRequirement?: string;
  designInstructions?: string;
  flyerPurpose?: string[];
  targetAudience?: string;
  agreements: string[];
  [key: string]: unknown;
}
