/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetConnectionStats200Data } from "./getConnectionStats200Data";

export type GetConnectionStats200 = {
  error?: string;
  data?: GetConnectionStats200Data;
  success: boolean;
};
