/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type GetConnectionStats200Data = {
  inactive: number;
  active: number;
  total: number;
};
