/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ConnectionResponse } from "./connectionResponse";

export type GetChatUsers200 = {
  data: ConnectionResponse[];
  success: boolean;
};
