/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FeedbackDto } from "./feedbackDto";

/**
 * @nullable
 */
export type GetFeedback200 = FeedbackDto | null;
