/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { MessageDto } from "./messageDto";

export type GetMessagesForProject200 = {
  take?: number;
  skip?: number;
  total: number;
  messages: MessageDto[];
};
