/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationDto } from "./notificationDto";

export type GetMyNotifications200 = {
  take?: number;
  skip?: number;
  unreadCount: number;
  total: number;
  notifications: NotificationDto[];
};
