/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessages200Data } from "./getMessages200Data";

export type GetMessages200 = {
  data?: GetMessages200Data;
  success: boolean;
};
