/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetOlderMessages200Data } from "./getOlderMessages200Data";

export type GetOlderMessages200 = {
  data?: GetOlderMessages200Data;
  success: boolean;
};
