/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentDto } from "./paymentDto";

/**
 * @nullable
 */
export type GetPayment200 = PaymentDto | null;
