/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewDto } from "./reviewDto";

export type GetReviewsForUser200 = {
  total: number;
  reviews: ReviewDto[];
};
