/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetSchedulerStatus200SchedulersItem } from "./getSchedulerStatus200SchedulersItem";

export type GetSchedulerStatus200 = {
  totalJobs: number;
  schedulers: GetSchedulerStatus200SchedulersItem[];
};
