/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { TaskDto } from "./taskDto";

/**
 * @nullable
 */
export type GetTask200 = TaskDto | null;
