/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsTaskStatus } from "./_36EnumsTaskStatus";

export type GetTasksForProjectParams = {
  assignedToId?: string;
  status?: _36EnumsTaskStatus;
  skip?: number;
  take?: number;
};
