/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";

export type GetUserProjectsParams = {
  /**
   * Optional project status to filter by.
   */
  status?: _36EnumsProjectStatus;
  /**
   * Optional pagination skip.
   */
  skip?: number;
  /**
   * Optional pagination take.
   */
  take?: number;
};
