/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokensDto } from "./authTokensDto";
import type { DefaultSelectionPrisma36UserPayload } from "./defaultSelectionPrisma36UserPayload";

export interface GoogleCallbackResponseDto {
  tokens: AuthTokensDto;
  user: DefaultSelectionPrisma36UserPayload;
  [key: string]: unknown;
}
