/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { InstagramPostRequirementAssets } from "./instagramPostRequirementAssets";
import type { InstagramPostRequirementReferences } from "./instagramPostRequirementReferences";

export interface InstagramPostRequirement {
  format: string[];
  goals: string[];
  headline: string;
  content: string;
  hashtags?: string[];
  tags?: string[];
  designStyle?: string[];
  colorRequirement?: string;
  assets?: InstagramPostRequirementAssets;
  references?: InstagramPostRequirementReferences;
  videoDuration?: string;
  captions?: boolean;
  narration?: string[];
  music?: string;
  scheduleNote?: string;
  agreements: string[];
  [key: string]: unknown;
}
