/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { InstagramPostProjectDtoDueDate } from "./instagramPostProjectDtoDueDate";
import type { InstagramPostProjectDtoPointsRequired } from "./instagramPostProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { InstagramPostRequirement } from "./instagramPostRequirement";

export interface InstagramPostProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: InstagramPostProjectDtoDueDate;
  pointsRequired?: InstagramPostProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: InstagramPostRequirement;
  [key: string]: unknown;
}
