/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { JsonValue } from "./jsonValue";

/**
 * From https://github.com/sindresorhus/type-fest/
Matches a JSON object.
This type can be useful to enforce some input to be JSON-compatible or as a super-type to be extended from.
 */
export interface JsonObject {
  [key: string]: JsonValue;
}
