/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * From https://github.com/sindresorhus/type-fest/
Matches a JSON array.
 */
export interface JsonArray {
  [key: string]: unknown;
}
