/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { JsonObject } from "./jsonObject";
import type { JsonArray } from "./jsonArray";

/**
 * From https://github.com/sindresorhus/type-fest/
Matches any valid JSON value.
 * @nullable
 */
export type JsonValue =
  | string
  | number
  | boolean
  | JsonObject
  | JsonArray
  | null;
