/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LineSetupProjectDtoDueDate } from "./lineSetupProjectDtoDueDate";
import type { LineSetupProjectDtoPointsRequired } from "./lineSetupProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { LineSetupRequirement } from "./lineSetupRequirement";

export interface LineSetupProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: LineSetupProjectDtoDueDate;
  pointsRequired?: LineSetupProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: LineSetupRequirement;
  [key: string]: unknown;
}
