/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LineSetupRequirementLineType } from "./lineSetupRequirementLineType";
import type { LineSetupRequirementAssets } from "./lineSetupRequirementAssets";
import type { LineSetupRequirementReferences } from "./lineSetupRequirementReferences";

export interface LineSetupRequirement {
  lineType: LineSetupRequirementLineType;
  goals: string[];
  productInfo: string;
  targetAudience: string;
  flow: string;
  stepMessages?: string[];
  richMenuItems?: string[];
  externalLinks?: string[];
  designPreference?: string;
  assets?: LineSetupRequirementAssets;
  references?: LineSetupRequirementReferences;
  notes?: string;
  midReviewSchedule?: string;
  agreements: string[];
  [key: string]: unknown;
}
