/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FileDto } from "./fileDto";

export type ListFilesByProjectId200 = {
  total: number;
  data: FileDto[];
};
