/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentDto } from "./paymentDto";

export type ListPayments200 = {
  take?: number;
  skip?: number;
  total: number;
  payments: PaymentDto[];
};
