/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LpEditRequirementChangesItem } from "./lpEditRequirementChangesItem";
import type { LpEditRequirementAssets } from "./lpEditRequirementAssets";

export interface LpEditRequirement {
  url: string;
  changes?: LpEditRequirementChangesItem[];
  assets?: LpEditRequirementAssets;
  editPurpose?: string[];
  agreements: string[];
  [key: string]: unknown;
}
