/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LpEditProjectDtoDueDate } from "./lpEditProjectDtoDueDate";
import type { LpEditProjectDtoPointsRequired } from "./lpEditProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { LpEditRequirement } from "./lpEditRequirement";

export interface LpEditProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: LpEditProjectDtoDueDate;
  pointsRequired?: LpEditProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: LpEditRequirement;
  [key: string]: unknown;
}
