/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface MessageDto {
  id: string;
  projectId: string;
  senderId: string;
  senderName?: string;
  senderAvatarUrl?: string;
  content: string;
  isRead: boolean;
  hasAttachment: boolean;
  /** @nullable */
  attachmentUrl?: string | null;
  createdAt: string;
  [key: string]: unknown;
}
