/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsNotificationType } from "./_36EnumsNotificationType";

export type NotificationType = _36EnumsNotificationType;
