/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsNotificationType } from "./_36EnumsNotificationType";

export interface NotificationDto {
  id: string;
  userId: string;
  title: string;
  content: string;
  type: _36EnumsNotificationType;
  isRead: boolean;
  /** @nullable */
  relatedId?: string | null;
  /** @nullable */
  relatedLink?: string | null;
  createdAt: string;
  [key: string]: unknown;
}
