/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId } from "./pickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId";

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitCreateProjectDtoClientIdOrFreelancerId =
  PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId;
