/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { OtherProjectDtoDueDate } from "./otherProjectDtoDueDate";
import type { OtherProjectDtoPointsRequired } from "./otherProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { RecordStringUnknown } from "./recordStringUnknown";

export interface OtherProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: OtherProjectDtoDueDate;
  pointsRequired?: OtherProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: RecordStringUnknown;
  [key: string]: unknown;
}
