/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FeedbackDto } from "./feedbackDto";
import type { PaginatedResultFeedbackDtoMeta } from "./paginatedResultFeedbackDtoMeta";

export interface PaginatedResultFeedbackDto {
  data: FeedbackDto[];
  meta?: PaginatedResultFeedbackDtoMeta;
  [key: string]: unknown;
}
