/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDto } from "./userResponseDto";
import type { PaginatedResultUserResponseDtoMeta } from "./paginatedResultUserResponseDtoMeta";

export interface PaginatedResultUserResponseDto {
  data: UserResponseDto[];
  meta?: PaginatedResultUserResponseDtoMeta;
  [key: string]: unknown;
}
