/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type PaginatedResultFeedbackDtoMeta = {
  totalPages?: number;
  pageSize?: number;
  page?: number;
  total?: number;
};
