/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectDto } from "./projectDto";
import type { PaginatedResultProjectDtoMeta } from "./paginatedResultProjectDtoMeta";

export interface PaginatedResultProjectDto {
  data: ProjectDto[];
  meta?: PaginatedResultProjectDtoMeta;
  [key: string]: unknown;
}
