/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PartialOmitCreateProjectDtoClientIdRequirement } from "./partialOmitCreateProjectDtoClientIdRequirement";
import type { PartialOmitCreateProjectDtoClientIdDueDate } from "./partialOmitCreateProjectDtoClientIdDueDate";
import type { PartialOmitCreateProjectDtoClientIdPointsRequired } from "./partialOmitCreateProjectDtoClientIdPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";

/**
 * Make all properties in T optional
 */
export interface PartialOmitCreateProjectDtoClientId {
  requirement?: PartialOmitCreateProjectDtoClientIdRequirement;
  title?: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: PartialOmitCreateProjectDtoClientIdDueDate;
  pointsRequired?: PartialOmitCreateProjectDtoClientIdPointsRequired;
  status?: _36EnumsProjectStatus;
  type?: _36EnumsProjectType;
  aiDetailedOverview?: string;
}
