/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Make all properties in T optional
 */
export interface PartialFileDto {
  [key: string]: unknown;
}
