/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { JsonValue } from "./jsonValue";
import type { _36EnumsFeedbackType } from "./_36EnumsFeedbackType";
import type { _36EnumsFeedbackStatus } from "./_36EnumsFeedbackStatus";
import type { PartialSubmissionDto } from "./partialSubmissionDto";

/**
 * Make all properties in T optional
 */
export interface PartialFeedbackDto {
  id?: string;
  projectId?: string;
  fileId?: string;
  createdById?: string;
  userName?: string;
  userAvatarUrl?: string;
  content?: string;
  timestamp?: JsonValue;
  type?: _36EnumsFeedbackType;
  status?: _36EnumsFeedbackStatus;
  rawContent?: string;
  instructionAudioFileId?: string;
  submission?: PartialSubmissionDto;
  createdAt?: string;
  updatedAt?: string;
}
