/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsSubmissionType } from "./_36EnumsSubmissionType";
import type { _36EnumsSubmissionStatus } from "./_36EnumsSubmissionStatus";
import type { PartialFileDto } from "./partialFileDto";

/**
 * Make all properties in T optional
 */
export interface PartialSubmissionDto {
  id?: string;
  projectId?: string;
  taskId?: string;
  submitterId?: string;
  title?: string;
  description?: string;
  type?: _36EnumsSubmissionType;
  status?: _36EnumsSubmissionStatus;
  version?: number;
  content?: unknown;
  files?: PartialFileDto[];
  submittedAt?: string;
  createdAt?: string;
  updatedAt?: string;
}
