/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsPaymentStatus } from "./_36EnumsPaymentStatus";

export type PaymentStatus = _36EnumsPaymentStatus;
