/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsPaymentStatus } from "./_36EnumsPaymentStatus";

export interface PaymentDto {
  id: string;
  projectId: string;
  projectTitle?: string;
  amount: number;
  status: _36EnumsPaymentStatus;
  /** @nullable */
  paymentMethod?: string | null;
  /** @nullable */
  transactionId?: string | null;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  description?: string | null;
  platformFee: number;
  freelancerAmount: number;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}
