/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36PaymentPayload } from "./defaultSelectionPrisma36PaymentPayload";

/**
 * Model Payment
 */
export type Payment = DefaultSelectionPrisma36PaymentPayload;
