/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdRequirement } from "./pickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdRequirement";
import type { PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdDueDate } from "./pickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdDueDate";
import type { PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdPointsRequired } from "./pickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId {
  requirement?: PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdRequirement;
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdDueDate;
  pointsRequired?: PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  aiDetailedOverview?: string;
}
