/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberAvatarUrl } from "./pickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberAvatarUrl";
import type { PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberSocialLinks } from "./pickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberSocialLinks";
import type { PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberSampleWorksItem } from "./pickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberSampleWorksItem";
import type { Decimal } from "./decimal";

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumber {
  name: string;
  email: string;
  avatarUrl?: PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberAvatarUrl;
  bio?: string;
  companyName?: string;
  industry?: string;
  plan?: string;
  bankName?: string;
  accountNumber?: string;
  accountName?: string;
  branchCode?: string;
  accountType?: string;
  tools?: string[];
  skills?: string[];
  position?: string;
  preferredStyles?: string[];
  specializations?: string[];
  experienceYears?: number;
  certifications?: string[];
  portfolioUrl?: string[];
  socialLinks?: PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberSocialLinks;
  sampleWorks?: PickSignUpDtoExcludeKeyofSignUpDtoPasswordOrClassificationOrPhoneNumberSampleWorksItem[];
  preferredVideoGenres?: string[];
  hourlyRate?: Decimal;
}
