/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LpEditRequirement } from "./lpEditRequirement";
import type { SeoArticleRequirement } from "./seoArticleRequirement";
import type { ThumbnailRequirement } from "./thumbnailRequirement";
import type { FlyerRequirement } from "./flyerRequirement";
import type { BannerRequirement } from "./bannerRequirement";
import type { VideoEditRequirement } from "./videoEditRequirement";
import type { ScriptRequirement } from "./scriptRequirement";
import type { BusinessCardRequirement } from "./businessCardRequirement";
import type { InstagramPostRequirement } from "./instagramPostRequirement";
import type { LineSetupRequirement } from "./lineSetupRequirement";
import type { RecordStringUnknown } from "./recordStringUnknown";

export type PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerIdRequirement =

    | LpEditRequirement
    | SeoArticleRequirement
    | ThumbnailRequirement
    | FlyerRequirement
    | BannerRequirement
    | VideoEditRequirement
    | ScriptRequirement
    | BusinessCardRequirement
    | InstagramPostRequirement
    | LineSetupRequirement
    | RecordStringUnknown;
