/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36TaskPayload } from "./defaultSelectionPrisma36TaskPayload";

export type ProcessInstructionAndCreateTasks200 = {
  tasks: DefaultSelectionPrisma36TaskPayload[];
  message: string;
};
