/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsUserAvalabilityStatus } from "./_36EnumsUserAvalabilityStatus";
import type { Decimal } from "./decimal";
import type { JsonValue } from "./jsonValue";
import type { ProfileDtoUser } from "./profileDtoUser";

export interface ProfileDto {
  availabilityStatus: _36EnumsUserAvalabilityStatus;
  userId: string;
  hourlyRate: Decimal;
  preferredVideoGenres: string[];
  sampleWorks: JsonValue;
  socialLinks: JsonValue;
  portfolioUrl: string[];
  certifications: string[];
  experienceYears: number;
  specializations: string[];
  preferredStyles: string[];
  position: string;
  skills: string[];
  tools: string[];
  accountType: string;
  branchCode: string;
  accountName: string;
  accountNumber: string;
  bankName: string;
  plan: string;
  industry: string;
  companyName: string;
  bio: string;
  id: string;
  user: ProfileDtoUser;
  [key: string]: unknown;
}
