/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsRole } from "./_36EnumsRole";

export type ProfileDtoUser = {
  createdAt?: string;
  reviewCount?: number;
  /** @nullable */
  averageRating?: number | null;
  points?: number;
  role: _36EnumsRole;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  name: string;
  email: string;
};
