/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36ProfilePayload } from "./defaultSelectionPrisma36ProfilePayload";

/**
 * Model Profile
 */
export type Profile = DefaultSelectionPrisma36ProfilePayload;
