/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PartialTaskDto } from "./partialTaskDto";
import type { PartialSubmissionDto } from "./partialSubmissionDto";
import type { PartialFeedbackDto } from "./partialFeedbackDto";
import type { ProjectDtoAllOfFreelancer } from "./projectDtoAllOfFreelancer";
import type { ProjectDtoAllOfClient } from "./projectDtoAllOfClient";

export type ProjectDtoAllOf = {
  currentOverviewVersion?: number;
  /** @nullable */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  tasks: PartialTaskDto[];
  submissions: PartialSubmissionDto[];
  feedbacks: PartialFeedbackDto[];
  /** @nullable */
  freelancer?: ProjectDtoAllOfFreelancer;
  client: ProjectDtoAllOfClient;
  id: string;
};
