/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";

export type ProjectStatus = _36EnumsProjectStatus;
