/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ProjectDtoAllOfFreelancer = {
  email: string;
  name: string;
  id: string;
} | null;
