/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId } from "./pickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId";
import type { ProjectDtoAllOf } from "./projectDtoAllOf";

export type ProjectDto =
  PickCreateProjectDtoExcludeKeyofCreateProjectDtoClientIdOrFreelancerId &
    ProjectDtoAllOf;
