/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectDtoAllOfClientProfile } from "./projectDtoAllOfClientProfile";

export type ProjectDtoAllOfClient = {
  profile: ProjectDtoAllOfClientProfile;
  email: string;
  /** @nullable */
  avatarUrl?: string | null;
  name: string;
  id: string;
};
