/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsProjectType } from "./_36EnumsProjectType";

export type ProjectType = _36EnumsProjectType;
