/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Construct a type with a set of properties K of type T
 */
export interface RecordStringUnknown {
  [key: string]: unknown;
}
