/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type ReviewDtoReviewer = {
  /** @nullable */
  avatarUrl: string | null;
  /** @nullable */
  name: string | null;
  id: string;
};
