/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface S3UploadDto {
  fileName: string;
  contentType: string;
  entityType: string;
  entityId?: string;
  purpose: string;
  [key: string]: unknown;
}
