/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ScriptRequirementReferences } from "./scriptRequirementReferences";

export interface ScriptRequirement {
  platforms: string[];
  videoLength: string;
  goals: string[];
  targetAudience: string;
  expectedReaction: string;
  scriptStyle: string[];
  tone?: string[];
  keyElements: string[];
  requiredPhrases?: string[];
  prohibitedWords?: string[];
  pastOwnPosts?: string[];
  references?: ScriptRequirementReferences;
  additionalNotes?: string;
  colorRequirement?: string;
  agreements: string[];
  [key: string]: unknown;
}
