/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ScriptProjectDtoDueDate } from "./scriptProjectDtoDueDate";
import type { ScriptProjectDtoPointsRequired } from "./scriptProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { ScriptRequirement } from "./scriptRequirement";

export interface ScriptProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: ScriptProjectDtoDueDate;
  pointsRequired?: ScriptProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: ScriptRequirement;
  [key: string]: unknown;
}
