/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DirectMessageInfo } from "./directMessageInfo";

export type SendMessage200 = {
  message?: string;
  data?: DirectMessageInfo;
  success: boolean;
};
