/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type SendMessageRequestType =
  (typeof SendMessageRequestType)[keyof typeof SendMessageRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendMessageRequestType = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  FILE: "FILE",
  AUDIO: "AUDIO",
  VIDEO: "VIDEO"
} as const;
