/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { SendMessageRequestType } from "./sendMessageRequestType";

export interface SendMessageRequest {
  receiverId: string;
  content: string;
  conversationId?: string;
  projectId?: string;
  type?: SendMessageRequestType;
  attachmentIds?: string[];
  [key: string]: unknown;
}
