/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { SeoArticleRequirementWordCount } from "./seoArticleRequirementWordCount";

export interface SeoArticleRequirement {
  publicationTarget: string;
  wordCount: SeoArticleRequirementWordCount;
  deliveryFormat: string;
  mainKeyword: string;
  subKeywords?: string[];
  searchIntent: string[];
  targetAudience?: string;
  articleStructure?: string[];
  referenceUrls?: string[];
  writingTone?: string;
  endingTone?: string;
  ctaDestination?: string;
  firstDraftReviewDate?: string;
  agreements: string[];
  [key: string]: unknown;
}
