/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { SeoArticleProjectDtoDueDate } from "./seoArticleProjectDtoDueDate";
import type { SeoArticleProjectDtoPointsRequired } from "./seoArticleProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { SeoArticleRequirement } from "./seoArticleRequirement";

export interface SeoArticleProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: SeoArticleProjectDtoDueDate;
  pointsRequired?: SeoArticleProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: SeoArticleRequirement;
  [key: string]: unknown;
}
