/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type SignUpDtoClassification =
  (typeof SignUpDtoClassification)[keyof typeof SignUpDtoClassification];

export const SignUpDtoClassification = {
  client: "client",
  freelance: "freelance"
} as const;
