/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { SignUpDtoSocialLinks } from "./signUpDtoSocialLinks";
import type { SignUpDtoSampleWorksItem } from "./signUpDtoSampleWorksItem";
import type { Decimal } from "./decimal";
import type { SignUpDtoAvatarUrl } from "./signUpDtoAvatarUrl";
import type { SignUpDtoClassification } from "./signUpDtoClassification";

export interface SignUpDto {
  companyName?: string;
  industry?: string;
  plan?: string;
  bankName?: string;
  accountNumber?: string;
  accountName?: string;
  branchCode?: string;
  accountType?: string;
  tools?: string[];
  skills?: string[];
  position?: string;
  preferredStyles?: string[];
  specializations?: string[];
  experienceYears?: number;
  certifications?: string[];
  portfolioUrl?: string[];
  socialLinks?: SignUpDtoSocialLinks;
  sampleWorks?: SignUpDtoSampleWorksItem[];
  preferredVideoGenres?: string[];
  hourlyRate?: Decimal;
  email: string;
  password: string;
  name: string;
  phoneNumber: string;
  avatarUrl?: SignUpDtoAvatarUrl;
  bio?: string;
  classification: SignUpDtoClassification;
  [key: string]: unknown;
}
