/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type StopScheduledJob200 = {
  jobName: string;
  message: string;
  success: boolean;
};
