/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsSubmissionStatus } from "./_36EnumsSubmissionStatus";

export type SubmissionStatus = _36EnumsSubmissionStatus;
