/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsSubmissionType } from "./_36EnumsSubmissionType";
import type { _36EnumsSubmissionStatus } from "./_36EnumsSubmissionStatus";
import type { SubmissionDtoContent } from "./submissionDtoContent";
import type { PartialFileDto } from "./partialFileDto";

export interface SubmissionDto {
  id: string;
  projectId: string;
  /** @nullable */
  taskId?: string | null;
  submitterId: string;
  title: string;
  /** @nullable */
  description?: string | null;
  type?: _36EnumsSubmissionType;
  status?: _36EnumsSubmissionStatus;
  version: number;
  /** @nullable */
  content?: SubmissionDtoContent;
  /** @nullable */
  files?: PartialFileDto[] | null;
  /** @nullable */
  submittedAt?: string | null;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}
