/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36TaskPayload } from "./defaultSelectionPrisma36TaskPayload";

/**
 * Model Task
 */
export type Task = DefaultSelectionPrisma36TaskPayload;
