/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { TestAllNotifications200OverdueNotifications } from "./testAllNotifications200OverdueNotifications";
import type { TestAllNotifications200DeadlineWarnings } from "./testAllNotifications200DeadlineWarnings";

export type TestAllNotifications200 = {
  error?: string;
  overdueNotifications: TestAllNotifications200OverdueNotifications;
  deadlineWarnings: TestAllNotifications200DeadlineWarnings;
  success: boolean;
};
