/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { ThumbnailRequirementSize } from "./thumbnailRequirementSize";
import type { ThumbnailRequirementAssets } from "./thumbnailRequirementAssets";
import type { ThumbnailRequirementReferences } from "./thumbnailRequirementReferences";
import type { ThumbnailRequirementMidReviewSchedule } from "./thumbnailRequirementMidReviewSchedule";

export interface ThumbnailRequirement {
  platforms: string[];
  videoTitle: string;
  size: ThumbnailRequirementSize;
  headline: string;
  desiredStyle?: string[];
  colorRequirement?: string;
  targetAudience?: string;
  assets?: ThumbnailRequirementAssets;
  references?: ThumbnailRequirementReferences;
  needsInitialCheck?: boolean;
  midReviewSchedule?: ThumbnailRequirementMidReviewSchedule;
  agreements: string[];
  [key: string]: unknown;
}
