/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { TriggerMultipleDeadlineWarnings200ResultsItem } from "./triggerMultipleDeadlineWarnings200ResultsItem";

export type TriggerMultipleDeadlineWarnings200 = {
  error?: string;
  results: TriggerMultipleDeadlineWarnings200ResultsItem[];
  success: boolean;
};
