/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { TriggerAllNotifications200OverdueNotifications } from "./triggerAllNotifications200OverdueNotifications";
import type { TriggerAllNotifications200DeadlineWarnings } from "./triggerAllNotifications200DeadlineWarnings";

export type TriggerAllNotifications200 = {
  error?: string;
  overdueNotifications: TriggerAllNotifications200OverdueNotifications;
  deadlineWarnings: TriggerAllNotifications200DeadlineWarnings;
  success: boolean;
};
