/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type TriggerDeadlineWarnings200 = {
  error?: string;
  projectsProcessed: number;
  notificationsCreated: number;
  success: boolean;
};
