/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type TriggerAllNotifications200DeadlineWarnings = {
  projectsProcessed: number;
  notificationsCreated: number;
};
