/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { PartialOmitCreateProjectDtoClientId } from "./partialOmitCreateProjectDtoClientId";
import type { UpdateProjectDtoAllOf } from "./updateProjectDtoAllOf";

export type UpdateProjectDto = PartialOmitCreateProjectDtoClientId &
  UpdateProjectDtoAllOf;
