/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProfileDtoSampleWorksItem = {
  updatedAt?: string;
  createdAt?: string;
  tags?: string[];
  thumbnailUrl?: string;
  url: string;
  description?: string;
  title: string;
};
