/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsPriority } from "./_36EnumsPriority";
import type { _36EnumsTaskStatus } from "./_36EnumsTaskStatus";

export interface UpdateTaskDto {
  assignedToId?: string;
  title?: string;
  description?: string;
  priority?: _36EnumsPriority;
  status?: _36EnumsTaskStatus;
  dueDate?: string;
  [key: string]: unknown;
}
