/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsFeedbackStatus } from "./_36EnumsFeedbackStatus";

export interface UpdateFeedbackDto {
  content?: string;
  status?: _36EnumsFeedbackStatus;
  [key: string]: unknown;
}
