/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * The new points value to set
 */
export type UpdateUserPointsBody = {
  points: number;
};
