/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfileDtoAvatarUrl } from "./updateProfileDtoAvatarUrl";
import type { UpdateProfileDtoSocialLinks } from "./updateProfileDtoSocialLinks";
import type { UpdateProfileDtoSampleWorksItem } from "./updateProfileDtoSampleWorksItem";
import type { Decimal } from "./decimal";
import type { _36EnumsUserAvalabilityStatus } from "./_36EnumsUserAvalabilityStatus";

export interface UpdateProfileDto {
  name?: string;
  phoneNumber?: string;
  avatarUrl?: UpdateProfileDtoAvatarUrl;
  bio?: string;
  companyName?: string;
  industry?: string;
  plan?: string;
  tools?: string[];
  skills?: string[];
  position?: string;
  preferredStyles?: string[];
  specializations?: string[];
  experienceYears?: number;
  certifications?: string[];
  portfolioUrl?: string[];
  socialLinks?: UpdateProfileDtoSocialLinks;
  sampleWorks?: UpdateProfileDtoSampleWorksItem[];
  preferredVideoGenres?: string[];
  hourlyRate?: Decimal;
  availabilityStatus?: _36EnumsUserAvalabilityStatus;
  [key: string]: unknown;
}
