/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36UserPayload } from "./defaultSelectionPrisma36UserPayload";

/**
 * Model User
 */
export type User = DefaultSelectionPrisma36UserPayload;
