/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreateDtoAvatarUrl } from "./userCreateDtoAvatarUrl";
import type { UserCreateDtoSocialLinks } from "./userCreateDtoSocialLinks";
import type { UserCreateDtoSampleWorksItem } from "./userCreateDtoSampleWorksItem";
import type { Decimal } from "./decimal";
import type { _36EnumsRole } from "./_36EnumsRole";

export interface UserCreateDto {
  name: string;
  email: string;
  avatarUrl?: UserCreateDtoAvatarUrl;
  bio?: string;
  companyName?: string;
  industry?: string;
  plan?: string;
  tools?: string[];
  skills?: string[];
  position?: string;
  preferredStyles?: string[];
  specializations?: string[];
  experienceYears?: number;
  certifications?: string[];
  portfolioUrl?: string[];
  socialLinks?: UserCreateDtoSocialLinks;
  sampleWorks?: UserCreateDtoSampleWorksItem[];
  preferredVideoGenres?: string[];
  hourlyRate?: Decimal;
  cognitoId?: string;
  role?: _36EnumsRole;
  phoneNumber?: string;
  points?: number;
  failedLoginAttempts?: number;
  lockedUntil?: string;
  lastFailedLoginAt?: string;
  [key: string]: unknown;
}
