/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateDtoAvatarUrl } from "./userUpdateDtoAvatarUrl";
import type { UserUpdateDtoSocialLinks } from "./userUpdateDtoSocialLinks";
import type { UserUpdateDtoSampleWorksItem } from "./userUpdateDtoSampleWorksItem";
import type { Decimal } from "./decimal";
import type { _36EnumsUserAvalabilityStatus } from "./_36EnumsUserAvalabilityStatus";

export interface UserUpdateDto {
  name?: string;
  email?: string;
  phoneNumber?: string;
  avatarUrl?: UserUpdateDtoAvatarUrl;
  bio?: string;
  companyName?: string;
  industry?: string;
  plan?: string;
  tools?: string[];
  skills?: string[];
  position?: string;
  preferredStyles?: string[];
  specializations?: string[];
  experienceYears?: number;
  certifications?: string[];
  portfolioUrl?: string[];
  socialLinks?: UserUpdateDtoSocialLinks;
  sampleWorks?: UserUpdateDtoSampleWorksItem[];
  preferredVideoGenres?: string[];
  hourlyRate?: Decimal;
  lastLoginAt?: string;
  availabilityStatus?: _36EnumsUserAvalabilityStatus;
  failedLoginAttempts?: number;
  lockedUntil?: string;
  lastFailedLoginAt?: string;
  [key: string]: unknown;
}
