/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsRole } from "./_36EnumsRole";
import type { UserResponseDtoProjectsAsFreelancerItem } from "./userResponseDtoProjectsAsFreelancerItem";

export interface UserResponseDto {
  deletedAt: string;
  updatedAt: string;
  createdAt: string;
  lastFailedLoginAt: string;
  lockedUntil: string;
  failedLoginAttempts: number;
  lastLoginAt: string;
  reviewCount: number;
  averageRating: number;
  points: number;
  isActive: boolean;
  avatarUrl: string;
  role: _36EnumsRole;
  phoneNumber: string;
  email: string;
  cognitoId: string;
  id: string;
  name: string;
  projectsAsFreelancer?: UserResponseDtoProjectsAsFreelancerItem[];
  [key: string]: unknown;
}
