/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { VideoEditProjectDtoDueDate } from "./videoEditProjectDtoDueDate";
import type { VideoEditProjectDtoPointsRequired } from "./videoEditProjectDtoPointsRequired";
import type { _36EnumsProjectStatus } from "./_36EnumsProjectStatus";
import type { _36EnumsProjectType } from "./_36EnumsProjectType";
import type { VideoEditRequirement } from "./videoEditRequirement";

export interface VideoEditProjectDto {
  title: string;
  description?: string;
  isPublic?: boolean;
  dueDate?: VideoEditProjectDtoDueDate;
  pointsRequired?: VideoEditProjectDtoPointsRequired;
  status?: _36EnumsProjectStatus;
  type: _36EnumsProjectType;
  clientId?: string;
  /** @nullable */
  aiDetailedOverview?: string | null;
  requirement?: VideoEditRequirement;
  [key: string]: unknown;
}
