/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { VideoEditRequirementAspectRatio } from "./videoEditRequirementAspectRatio";
import type { VideoEditRequirementRawVideo } from "./videoEditRequirementRawVideo";
import type { VideoEditRequirementAssets } from "./videoEditRequirementAssets";
import type { VideoEditRequirementReferences } from "./videoEditRequirementReferences";
import type { VideoEditRequirementCaptions } from "./videoEditRequirementCaptions";

export interface VideoEditRequirement {
  videoUsage: string[];
  videoLength: string;
  aspectRatio: VideoEditRequirementAspectRatio;
  rawVideo: VideoEditRequirementRawVideo;
  assets?: VideoEditRequirementAssets;
  references?: VideoEditRequirementReferences;
  bgm?: string;
  editStyle?: string[];
  captions: VideoEditRequirementCaptions;
  cutInstructions?: string;
  insertGraphics?: string;
  ngWords?: string;
  additionalInstructions?: string;
  targetAudience?: string;
  needsInitialCheck?: boolean;
  midReviewSchedule?: string;
  agreements: string[];
  [key: string]: unknown;
}
