/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { UnlockAccountResponse } from "../../model";

import { customInstance } from "../../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAdminAccountSecurity = () => {
  /**
   * Unlock a user account (Admin only)
   */
  const unlockAccount = (
    userId: string,
    options?: SecondParameter<typeof customInstance>
  ) => {
    return customInstance<UnlockAccountResponse>(
      { url: `/admin/account-security/${userId}/unlock`, method: "POST" },
      options
    );
  };
  return { unlockAccount };
};
export type UnlockAccountResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAdminAccountSecurity>["unlockAccount"]>
  >
>;
