import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import CustomSessionProvider from "@/contexts/CustomSessionProvider";
import { Toaster } from "sonner";
import { ProgressProvider } from "@/contexts/ProgressProvider";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${publicSans.className} antialiased`}>
      <body>
        <ProgressProvider>
          <CustomSessionProvider>{children}</CustomSessionProvider>
        </ProgressProvider>
        <Toaster position="top-center" richColors expand={false} />
      </body>
    </html>
  );
}
