import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import CustomSessionProvider from "@/contexts/CustomSessionProvider";
import { Toaster } from "sonner";

const publicSans = Public_Sans({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${publicSans.className} antialiased`}>
        <CustomSessionProvider>{children}</CustomSessionProvider>
        <Toaster position="top-center" richColors expand={false} />
      </body>
    </html>
  );
}
