/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type {
  S3UploadDto,
  S3UploadResponseDto,
  _Delete200,
  _DeleteBody
} from "../../model";

import { customInstance } from "../../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getS3FileUpload = () => {
  const upload = (
    s3UploadDto: S3UploadDto,
    options?: SecondParameter<typeof customInstance>
  ) => {
    return customInstance<S3UploadResponseDto>(
      {
        url: `/file/upload`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: s3UploadDto
      },
      options
    );
  };
  const _delete = (
    _deleteBody: _DeleteBody,
    options?: SecondParameter<typeof customInstance>
  ) => {
    return customInstance<_Delete200>(
      {
        url: `/file/delete`,
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        data: _deleteBody
      },
      options
    );
  };
  return { upload, _delete };
};
export type UploadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getS3FileUpload>["upload"]>>
>;
export type _DeleteResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getS3FileUpload>["_delete"]>>
>;
